#!/usr/bin/env bash

num_calls=100
first_dir="/home/me/kingston1"
second_dir="/home/me/kingston2"
# num_calls=100
# first_dir="/home/me/Books1/"
# second_dir="/home/me/Books2"

bash_tests() {
	# {{{
	echo "Running Bash version of cmp-tree $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		bash/cmp-tree/cmp-tree ${first_dir} ${second_dir} &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "cmp-tree (Bash): $num_calls calls took a total of ${total_execution_time}s"
	echo "cmp-tree (Bash): On average, each execution took ${average_execution_time}s"
	# }}}
}


cpp_tests() {
	# {{{
	echo "Running C++ version of cmp-tree $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		cpp/cmp-tree/cmp-tree ${first_dir} ${second_dir} &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "cmp-tree (C++): $num_calls calls took a total of ${total_execution_time}s"
	echo "cmp-tree (C++): On average, each execution took ${average_execution_time}s"
	# }}}
}


c_tests() {
	# {{{
	echo "Running C version of cmp-tree $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		c/cmp-tree/cmp-tree ${first_dir} ${second_dir} &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "cmp-tree (C): $num_calls calls took a total of ${total_execution_time}s"
	echo "cmp-tree (C): On average, each execution took ${average_execution_time}s"
	# }}}
}


rust_tests() {
	# {{{
	cd rust/cmp-tree
	echo "Running Rust version of cmp-tree $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		target/release/cmp-tree ${first_dir} ${second_dir} &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "cmp-tree (Rust): $num_calls calls took a total of ${total_execution_time}s"
	echo "cmp-tree (Rust): On average, each execution took ${average_execution_time}s"
	cd ../..
	# }}}
}


python_tests() {
	# {{{
	cd python/cmp-tree
	echo "Running Python version of cmp-tree $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		python cmp-tree.py ${first_dir} ${second_dir} &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "cmp-tree (Python): $num_calls calls took a total of ${total_execution_time}s"
	echo "cmp-tree (Python): On average, each execution took ${average_execution_time}s"
	cd ../..
	# }}}
}


diff_tests() {
	# {{{
	echo "Running diff $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		diff -qr ${first_dir} ${second_dir} &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "diff: $num_calls calls took a total of ${total_execution_time}s"
	echo "diff: On average, each execution took ${average_execution_time}s"
	# }}}
}


rsync_tests() {
	# {{{
	echo "Running rsync $num_calls times..."
	start=$(date +%s.%N)

	for i in $(seq $num_calls); do
		# It's important to note a couple things about the rsync command used
		# here: First, the command does not exit with a non-zero exit code if
		# there are any differences in the two directory trees. Second, you
		# must end the path to the directories that root each directory tree
		# with a "/".
		rsync -nrvc --delete kingston1/ kingston2/ &> /dev/null
	done

	end=$(date +%s.%N)
	total_execution_time=$(echo "$end - $start" | bc -l)
	average_execution_time=$(echo "($end - $start) / $num_calls" | bc -l)

	echo "rsync: $num_calls calls took a total of ${total_execution_time}s"
	echo "rsync: On average, each execution took ${average_execution_time}s"
	# }}}
}


# bash_tests
cpp_tests
c_tests
rust_tests
python_tests
diff_tests
rsync_tests
